### ISSUE TITLE
Put the cat pictures on README.md

### ISSUE THREAD

**Issue by ryukinix** [DestructHub/cats#10]
That way we can improve the visualization of the cats. Separate each header as a individual cat with its photos, like:

```
# Description

A cat repo

#  Cats
## Antares
![pic1](pic1)
## Miaura
![pic2](pic2)
![pic3](pic3)


```

**Comment by mateusfccp** [comment]
Are you suggesting putting all the photos or one of each cat?

**Comment by ryukinix** [comment]
@mateusfccp all!

**Comment by mateusfccp** [comment]
How about we put one of the photos as a demonstrative and the remaining within details? Like:

<details>
<summary>More photos of Miaura</summary>
... photo 1 ...
... photo 2 ...
... photo 2 ...
</details>

**Comment by ryukinix** [comment]
I liked it! @mateusfccp

**Comment by mateusfccp** [comment]
@ryukinix 
I am a little busy right now with my DevFest presentation, so I will be able to get on this only next week, ok?

**Comment by ryukinix** [comment]
Ok!

**Comment by mateusfccp** [comment]
@ryukinix I think this issue can be closed?

**Comment by ryukinix** [comment]
Yes, I'm closing it. Thank you! It's now a mastercatpiece
